name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          cd pcp_utils
          go build ./...
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: sign_artefact
          path: pcp_utils/sign_artefact
